# App-level ProGuard / R8 rules.
#
# The Pisano native SDK layer (consumed by the Flutter plugin) may reference
# optional platform integrations. In release builds with R8 enabled, these can
# surface as "Missing class" errors even though the code paths are optional.
#
# These rules are based on the autogenerated output:
# `build/app/outputs/mapping/release/missing_rules.txt`

-dontwarn com.google.android.gms.tasks.OnCompleteListener
-dontwarn com.google.android.gms.tasks.Task
-dontwarn com.google.android.play.core.review.ReviewManager
-dontwarn com.google.android.play.core.review.ReviewManagerFactory
-dontwarn org.bouncycastle.jsse.BCSSLParameters
-dontwarn org.bouncycastle.jsse.BCSSLSocket
-dontwarn org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
-dontwarn org.conscrypt.Conscrypt$Version
-dontwarn org.conscrypt.Conscrypt
-dontwarn org.conscrypt.ConscryptHostnameVerifier
-dontwarn org.openjsse.javax.net.ssl.SSLParameters
-dontwarn org.openjsse.javax.net.ssl.SSLSocket
-dontwarn org.openjsse.net.ssl.OpenJSSE

